### ISSUE TITLE
Helm repo issue

### ISSUE THREAD

**Issue by atalakey4work** [supabase-community/supabase-kubernetes#18]
Unable to add helm repo due to below error:

Command used: helm repo add supabase https://supabase-community.github.io/supabase-kubernetes

Helm version: v3.9.0

Error message: looks like "https://supabase-community.github.io/supabase-kubernetes" is not a valid chart repository or cannot be reached: failed to fetch https://supabase-community.github.io/supabase-kubernetes/index.yaml : 404 Not Found

**Comment by windhamwong** [comment]
use this way
1. git clone
2. helm install RELEASE_NAME . -f values.yaml ...............

**Comment by zabealbe** [comment]
You can use

**Comment by ACK-lcn** [comment]
When will the new version of the helm3 chart package be released? I see that the previous charts package has bugs
