### ISSUE TITLE
Defaulting to :latest Tag Pulls Old Versions of Supabase

### ISSUE THREAD

**Issue by yeldarby** [supabase-community/supabase-kubernetes#28]
# Bug report

## Describe the bug

The helm chart in this repo doesn't specify a tag for the containers which pulls `:latest`, but Supabase stopped updating the latest tags along with new releases 5-6 months ago so by default your Kubernetes deployment ends up way out of date with this repo.

## To Reproduce

Spin up a Kubernetes cluster with this repo

## Expected behavior

You have a current version of Supabase

## Screenshots

<img width="615" alt="image" src="https://user-images.githubusercontent.com/870796/214372095-244cf9b3-5d8a-400f-81cf-36c799bb1e61.png">

## System information

Not relevant

## Additional context

The [official Supabase docker-compose.yaml](https://github.com/supabase/supabase/blob/master/docker/docker-compose.yml) specifies specific tags for each image.

**Comment by bigbitbus** [comment]
Closing this since the newer helm chart  version has updated docker image versions.
