### ISSUE TITLE
What should STUDIO_PG_META_URL point to?

### ISSUE THREAD

**Issue by kubeworkz** [supabase-community/supabase-kubernetes#32]
I'm currently setting STUDIO_PG_META_URL to: `http://cloudrock-supabase-kong.default.svc.cluster.local:8000/pg` in the `studio` section of my `values.yaml` file and I'm getting the following error:
```
Error: [500] self signed certificate
```
It happens in the table editor, database etc. I guess wherever it's trying to communicate with Kong? 

Cheers, Dave

**Comment by bigbitbus** [comment]
Hi @kubeworkz 

Can you paste more of your values file used to deploy the chart, and which chart version are you using?

**Comment by kubeworkz** [comment]
[values.tar.gz](https://github.com/supabase-community/supabase-kubernetes/files/10715166/values.tar.gz)

The chart version is: 0.0.2

**Comment by bigbitbus** [comment]
Cool, if its running then can you close the issue?

**Comment by kubeworkz** [comment]
oops, I wasn't detailed enough. It's partially running. If you try the Table Editor or Database menu items you'll see the error.
My theory is that the call to Kong uses http and everything else is https. I need to get the proper certs down to Kong. There's a mismatch there somewhere. Cheers, Dave

**Comment by bigbitbus** [comment]
Are you terminating the SSL in nginx or Kong directly?

I have had success with using the current helm chart as a starting point and then putting an nginx ingress in front of it for routing and TLS termination, I havent looked at using Kong directly for TLS termination.

**Comment by kubeworkz** [comment]
Hi @bigbitbus 

I did some digging yesterday and I found this: https://support.konghq.com/support/s/article/How-to-setup-Kong-to-serve-an-SSL-certificate-for-API-requests

I'm pretty sure this would solve the issue if I can get the proper cert on the Kong pod. I should be able to call `https://RELEASE-supabase-kong.default.svc.cluster.local:8444/pg` from within `values.yaml`.

**Comment by kubeworkz** [comment]
Thanks, I'll check that out. Yes, I was doing it directly. You wouldn't have a snippet of how you did that would you? 

btw: I found this doc yesterday. https://support.konghq.com/support/s/article/How-to-setup-Kong-to-serve-an-SSL-certificate-for-API-requests. It looks as though Kong puts its' own certs in there initially so they can do https on localhost.

**Comment by bigbitbus** [comment]
I basically went to cert-manager documentation route for the nginx ingress 

https://cert-manager.io/docs/tutorials/acme/nginx-ingress/

Since the SSL terminated outside of the whole Supabase setup, SSL was not an issue.

**Comment by kubeworkz** [comment]
So you added an Issuer / Ingress etc. to your cluster itself and skipped the kong entry in values.yaml?

**Comment by kubeworkz** [comment]
Down to one series of errors: `Load error message relation "public.extensions" does not exist` (basically public.anything)...sooo close.

**Comment by kubeworkz** [comment]
Yep, the cert manager route worked, thanks. Is there a way to seed the Supabase database anywhere?

**Comment by kubeworkz** [comment]
I got everything working! Turns out I just needed to disable ssl on `DB_SSL` (everywhere). I also added a few things to the database structure (not sure if they're needed)
```
Extensions
 - pg_graphql
 - pg_stat_statements

Schema
 - graphql_public
```
Thanks for your guidance, very much appreciated.
