### ISSUE TITLE
Yamls need clean up

### ISSUE THREAD

**Issue by davidliudev** [supabase-community/supabase-kubernetes#35]
Just notice some of the data in values are confusing.

For example, in values.yaml:

 ingress:
    enabled: true
    className: "nginx"
    annotations:
      nginx.ingress.kubernetes.io/rewrite-target: /
    tls: []
      # - secretName: localhost
      #   hosts:
      #     - localhost
    hosts:
      - host: localhost
        paths:
          - path: /
            pathType: Prefix
            backend:
              serviceName: api
              servicePort: 80

There is a service name specified (api). However that service name is not used.

In Ingress.yaml for kong,

 paths:
          {{- range .paths }}
          - path: {{ .path }}
            {{- if and .pathType (semverCompare ">=1.18-0" $.Capabilities.KubeVersion.GitVersion) }}
            pathType: {{ .pathType }}
            {{- end }}
            backend:
              {{- if semverCompare ">=1.19-0" $.Capabilities.KubeVersion.GitVersion }}
              service:
                name: {{ $fullName }}
                port:
                  number: {{ $svcPort }}
              {{- else }}
              serviceName: {{ $fullName }}
              servicePort: {{ $svcPort }}
              {{- end }}
          {{- end }}

The serviceName uses $fullName which is defined in the top:
{{- $fullName := include "supabase.kong.fullname" . -}}

This is very confusing since we have to look through each individual template to figure out which one works.

**Comment by bigbitbus** [comment]
Hi @davidliudev; thanks for flagging these issues. 

I am one of the maintainers of the chart; do you think you could submit a PR and we could work together on improving the yamls? Happy to review your suggestions and incorporate them into the chart.
