### ISSUE TITLE
Supabase Dashboard Logs

### ISSUE THREAD

**Issue by diogo-logrado-unp** [supabase-community/supabase-kubernetes#68]
# Bug report

## Describe the bug

The logs explorer is not showing any logs

## To Reproduce

Steps to reproduce:

1. Selecting any API logs from the 'Logs' tab
2. Query any logs from the 'Logs' tab

## Expected behavior

Logs should show for the APIs.

## Screenshots

Empty logs
![Screenshot 2024-05-29 at 12 17 43](https://github.com/supabase-community/supabase-kubernetes/assets/165292802/afe01452-1ad8-44cd-8991-203f1425d91f)

Empty queries
![Screenshot 2024-05-29 at 12 25 50](https://github.com/supabase-community/supabase-kubernetes/assets/165292802/bd1ea8c3-26d0-4609-b23e-92e3daddc325)

## System information

- OS: Ubuntu 22.04.4

## Additional context

We already meddled with the values.yaml, enabled all services(analytics included), kong_level is on "info"...

The vector service seems to have some issues. 
ERROR sink{component_kind="sink" component_id=logflare_realtime component_type=http}:request{request_id=91823}: vector_common::internal_event::component_events_dropped: Internal log [Events dropped] is being suppressed to avoid flooding.

Any questions please ask.

**Comment by diogo-logrado-unp** [comment]
> Did you solve this? I didn't have this issue and then it popped up when changing a few configurations recently

No, I still don't get any logs. If I ever find a solution I will probably post it here and mark it answered

**Comment by nickmitchko** [comment]
> > Did you solve this? I didn't have this issue and then it popped up when changing a few configurations recently
> 
> No, I still don't get any logs. If I ever find a solution I will probably post it here and mark it answered

I figured it out. The studio versions and the logging versions need to mesh nicely. If you try studio:latest or logging:latest in this chart it fails. Here's my configuration that works now.

```
supabase/studio:20240422-e602d1e
supabase/postgres-meta:v0.83.0
supabase/logflare:1.4.0
```

**Comment by diogo-logrado-unp** [comment]
> Something with your auth. Can you share your entire values configuration?

You mean my entire values.yaml or just the auth part. Can you be more specific on what are you hoping to find so we can share here. There is some sensitive information there and cleaning the document could take some time. Sorry for the delayed replies.
