### ISSUE TITLE
Auth error: tenant `backend-supabase-realtime` not found

### ISSUE THREAD

**Issue by cmrwy** [supabase-community/supabase-kubernetes#74]
# Bug report

## Describe the bug

Realtime does not work, getting websocket connection errors in Browser Console. The pod logs of realtime show the following error: 
```
12:08:43.796 project=backend-supabase-realtime external_id=backend-supabase-realtime [error] Auth error: tenant `backend-supabase-realtime` not found
```

Apparently `realtime-dev` would be the correct tenant value, but I can't find where to configure this. `backend-supabase-realtime` is the deployment name of the service which was automatically generated during helm deployment.

## To Reproduce

1. Deploy chart
2. Try to access the realtime websocket

## Expected behavior

Realtime websocket can be properly accessed

## Screenshots

Entry in `_realtime` Schema, generated by the same stack:
![image](https://github.com/supabase-community/supabase-kubernetes/assets/165819833/b184f950-c2d7-4eb2-8720-3fd9f67b9573)

## System information

- OS: macOS client-side, Ubuntu 20.04 with k3s server-side
- Browser (if applies): Chrome
- Version of supabase-js: ^2.43.4
- Version of Node.js: current LTS

**Comment by cmrwy** [comment]
adding `Values.realtime.fullnameOverride` to `realtime-dev` in the values and recreating auth, kong and realtime pods seems to have fixed it for me.

**Comment by nickmitchko** [comment]
How did you figure out the proper fullnameOverride?

**Comment by cmrwy** [comment]
@nickmitchko The official docker-compose stack uses this as container name

**Comment by nickmitchko** [comment]
Found the offending line of code: 

https://github.com/supabase/realtime/blob/a82bdf6c20c7d2c7a1da4fe7b8a2d8d19b9436d2/priv/repo/seeds.exs#L4

Not sure why this is needed, but I believe we can edit this to take an OS variable or a post migration script.
